// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: pkg/connectionmanager/grpc/quarkcmsvc.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuarkCMServiceClient is the client API for QuarkCMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuarkCMServiceClient interface {
	// Test
	TestPing(ctx context.Context, in *TestRequestMessage, opts ...grpc.CallOption) (*TestResponseMessage, error)
	ListNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeListMessage, error)
	WatchNode(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchNodeClient, error)
	ListPod(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PodListMessage, error)
	WatchPod(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchPodClient, error)
	ListService(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceListMessage, error)
	WatchService(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchServiceClient, error)
	ListEndpoints(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EndpointsListMessage, error)
	WatchEndpoints(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchEndpointsClient, error)
	ListConfigMap(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ConfigMapListMessage, error)
	WatchConfigMap(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchConfigMapClient, error)
	ListIngress(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IngressListMessage, error)
	WatchIngress(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchIngressClient, error)
	ListRdmaIngress(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RdmaIngressListMessage, error)
	WatchRdmaIngress(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchRdmaIngressClient, error)
}

type quarkCMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuarkCMServiceClient(cc grpc.ClientConnInterface) QuarkCMServiceClient {
	return &quarkCMServiceClient{cc}
}

func (c *quarkCMServiceClient) TestPing(ctx context.Context, in *TestRequestMessage, opts ...grpc.CallOption) (*TestResponseMessage, error) {
	out := new(TestResponseMessage)
	err := c.cc.Invoke(ctx, "/quarkcmsvc.QuarkCMService/TestPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quarkCMServiceClient) ListNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeListMessage, error) {
	out := new(NodeListMessage)
	err := c.cc.Invoke(ctx, "/quarkcmsvc.QuarkCMService/ListNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quarkCMServiceClient) WatchNode(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchNodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &QuarkCMService_ServiceDesc.Streams[0], "/quarkcmsvc.QuarkCMService/WatchNode", opts...)
	if err != nil {
		return nil, err
	}
	x := &quarkCMServiceWatchNodeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QuarkCMService_WatchNodeClient interface {
	Recv() (*NodeMessage, error)
	grpc.ClientStream
}

type quarkCMServiceWatchNodeClient struct {
	grpc.ClientStream
}

func (x *quarkCMServiceWatchNodeClient) Recv() (*NodeMessage, error) {
	m := new(NodeMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *quarkCMServiceClient) ListPod(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PodListMessage, error) {
	out := new(PodListMessage)
	err := c.cc.Invoke(ctx, "/quarkcmsvc.QuarkCMService/ListPod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quarkCMServiceClient) WatchPod(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchPodClient, error) {
	stream, err := c.cc.NewStream(ctx, &QuarkCMService_ServiceDesc.Streams[1], "/quarkcmsvc.QuarkCMService/WatchPod", opts...)
	if err != nil {
		return nil, err
	}
	x := &quarkCMServiceWatchPodClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QuarkCMService_WatchPodClient interface {
	Recv() (*PodMessage, error)
	grpc.ClientStream
}

type quarkCMServiceWatchPodClient struct {
	grpc.ClientStream
}

func (x *quarkCMServiceWatchPodClient) Recv() (*PodMessage, error) {
	m := new(PodMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *quarkCMServiceClient) ListService(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceListMessage, error) {
	out := new(ServiceListMessage)
	err := c.cc.Invoke(ctx, "/quarkcmsvc.QuarkCMService/ListService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quarkCMServiceClient) WatchService(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &QuarkCMService_ServiceDesc.Streams[2], "/quarkcmsvc.QuarkCMService/WatchService", opts...)
	if err != nil {
		return nil, err
	}
	x := &quarkCMServiceWatchServiceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QuarkCMService_WatchServiceClient interface {
	Recv() (*ServiceMessage, error)
	grpc.ClientStream
}

type quarkCMServiceWatchServiceClient struct {
	grpc.ClientStream
}

func (x *quarkCMServiceWatchServiceClient) Recv() (*ServiceMessage, error) {
	m := new(ServiceMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *quarkCMServiceClient) ListEndpoints(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EndpointsListMessage, error) {
	out := new(EndpointsListMessage)
	err := c.cc.Invoke(ctx, "/quarkcmsvc.QuarkCMService/ListEndpoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quarkCMServiceClient) WatchEndpoints(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchEndpointsClient, error) {
	stream, err := c.cc.NewStream(ctx, &QuarkCMService_ServiceDesc.Streams[3], "/quarkcmsvc.QuarkCMService/WatchEndpoints", opts...)
	if err != nil {
		return nil, err
	}
	x := &quarkCMServiceWatchEndpointsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QuarkCMService_WatchEndpointsClient interface {
	Recv() (*EndpointsMessage, error)
	grpc.ClientStream
}

type quarkCMServiceWatchEndpointsClient struct {
	grpc.ClientStream
}

func (x *quarkCMServiceWatchEndpointsClient) Recv() (*EndpointsMessage, error) {
	m := new(EndpointsMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *quarkCMServiceClient) ListConfigMap(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ConfigMapListMessage, error) {
	out := new(ConfigMapListMessage)
	err := c.cc.Invoke(ctx, "/quarkcmsvc.QuarkCMService/ListConfigMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quarkCMServiceClient) WatchConfigMap(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchConfigMapClient, error) {
	stream, err := c.cc.NewStream(ctx, &QuarkCMService_ServiceDesc.Streams[4], "/quarkcmsvc.QuarkCMService/WatchConfigMap", opts...)
	if err != nil {
		return nil, err
	}
	x := &quarkCMServiceWatchConfigMapClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QuarkCMService_WatchConfigMapClient interface {
	Recv() (*ConfigMapMessage, error)
	grpc.ClientStream
}

type quarkCMServiceWatchConfigMapClient struct {
	grpc.ClientStream
}

func (x *quarkCMServiceWatchConfigMapClient) Recv() (*ConfigMapMessage, error) {
	m := new(ConfigMapMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *quarkCMServiceClient) ListIngress(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IngressListMessage, error) {
	out := new(IngressListMessage)
	err := c.cc.Invoke(ctx, "/quarkcmsvc.QuarkCMService/ListIngress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quarkCMServiceClient) WatchIngress(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchIngressClient, error) {
	stream, err := c.cc.NewStream(ctx, &QuarkCMService_ServiceDesc.Streams[5], "/quarkcmsvc.QuarkCMService/WatchIngress", opts...)
	if err != nil {
		return nil, err
	}
	x := &quarkCMServiceWatchIngressClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QuarkCMService_WatchIngressClient interface {
	Recv() (*IngressMessage, error)
	grpc.ClientStream
}

type quarkCMServiceWatchIngressClient struct {
	grpc.ClientStream
}

func (x *quarkCMServiceWatchIngressClient) Recv() (*IngressMessage, error) {
	m := new(IngressMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *quarkCMServiceClient) ListRdmaIngress(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RdmaIngressListMessage, error) {
	out := new(RdmaIngressListMessage)
	err := c.cc.Invoke(ctx, "/quarkcmsvc.QuarkCMService/ListRdmaIngress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quarkCMServiceClient) WatchRdmaIngress(ctx context.Context, in *MaxResourceVersionMessage, opts ...grpc.CallOption) (QuarkCMService_WatchRdmaIngressClient, error) {
	stream, err := c.cc.NewStream(ctx, &QuarkCMService_ServiceDesc.Streams[6], "/quarkcmsvc.QuarkCMService/WatchRdmaIngress", opts...)
	if err != nil {
		return nil, err
	}
	x := &quarkCMServiceWatchRdmaIngressClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QuarkCMService_WatchRdmaIngressClient interface {
	Recv() (*RdmaIngressMessage, error)
	grpc.ClientStream
}

type quarkCMServiceWatchRdmaIngressClient struct {
	grpc.ClientStream
}

func (x *quarkCMServiceWatchRdmaIngressClient) Recv() (*RdmaIngressMessage, error) {
	m := new(RdmaIngressMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// QuarkCMServiceServer is the server API for QuarkCMService service.
// All implementations must embed UnimplementedQuarkCMServiceServer
// for forward compatibility
type QuarkCMServiceServer interface {
	// Test
	TestPing(context.Context, *TestRequestMessage) (*TestResponseMessage, error)
	ListNode(context.Context, *emptypb.Empty) (*NodeListMessage, error)
	WatchNode(*MaxResourceVersionMessage, QuarkCMService_WatchNodeServer) error
	ListPod(context.Context, *emptypb.Empty) (*PodListMessage, error)
	WatchPod(*MaxResourceVersionMessage, QuarkCMService_WatchPodServer) error
	ListService(context.Context, *emptypb.Empty) (*ServiceListMessage, error)
	WatchService(*MaxResourceVersionMessage, QuarkCMService_WatchServiceServer) error
	ListEndpoints(context.Context, *emptypb.Empty) (*EndpointsListMessage, error)
	WatchEndpoints(*MaxResourceVersionMessage, QuarkCMService_WatchEndpointsServer) error
	ListConfigMap(context.Context, *emptypb.Empty) (*ConfigMapListMessage, error)
	WatchConfigMap(*MaxResourceVersionMessage, QuarkCMService_WatchConfigMapServer) error
	ListIngress(context.Context, *emptypb.Empty) (*IngressListMessage, error)
	WatchIngress(*MaxResourceVersionMessage, QuarkCMService_WatchIngressServer) error
	ListRdmaIngress(context.Context, *emptypb.Empty) (*RdmaIngressListMessage, error)
	WatchRdmaIngress(*MaxResourceVersionMessage, QuarkCMService_WatchRdmaIngressServer) error
	mustEmbedUnimplementedQuarkCMServiceServer()
}

// UnimplementedQuarkCMServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQuarkCMServiceServer struct {
}

func (UnimplementedQuarkCMServiceServer) TestPing(context.Context, *TestRequestMessage) (*TestResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestPing not implemented")
}
func (UnimplementedQuarkCMServiceServer) ListNode(context.Context, *emptypb.Empty) (*NodeListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNode not implemented")
}
func (UnimplementedQuarkCMServiceServer) WatchNode(*MaxResourceVersionMessage, QuarkCMService_WatchNodeServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchNode not implemented")
}
func (UnimplementedQuarkCMServiceServer) ListPod(context.Context, *emptypb.Empty) (*PodListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPod not implemented")
}
func (UnimplementedQuarkCMServiceServer) WatchPod(*MaxResourceVersionMessage, QuarkCMService_WatchPodServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchPod not implemented")
}
func (UnimplementedQuarkCMServiceServer) ListService(context.Context, *emptypb.Empty) (*ServiceListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListService not implemented")
}
func (UnimplementedQuarkCMServiceServer) WatchService(*MaxResourceVersionMessage, QuarkCMService_WatchServiceServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchService not implemented")
}
func (UnimplementedQuarkCMServiceServer) ListEndpoints(context.Context, *emptypb.Empty) (*EndpointsListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEndpoints not implemented")
}
func (UnimplementedQuarkCMServiceServer) WatchEndpoints(*MaxResourceVersionMessage, QuarkCMService_WatchEndpointsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchEndpoints not implemented")
}
func (UnimplementedQuarkCMServiceServer) ListConfigMap(context.Context, *emptypb.Empty) (*ConfigMapListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigMap not implemented")
}
func (UnimplementedQuarkCMServiceServer) WatchConfigMap(*MaxResourceVersionMessage, QuarkCMService_WatchConfigMapServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchConfigMap not implemented")
}
func (UnimplementedQuarkCMServiceServer) ListIngress(context.Context, *emptypb.Empty) (*IngressListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIngress not implemented")
}
func (UnimplementedQuarkCMServiceServer) WatchIngress(*MaxResourceVersionMessage, QuarkCMService_WatchIngressServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchIngress not implemented")
}
func (UnimplementedQuarkCMServiceServer) ListRdmaIngress(context.Context, *emptypb.Empty) (*RdmaIngressListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRdmaIngress not implemented")
}
func (UnimplementedQuarkCMServiceServer) WatchRdmaIngress(*MaxResourceVersionMessage, QuarkCMService_WatchRdmaIngressServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchRdmaIngress not implemented")
}
func (UnimplementedQuarkCMServiceServer) mustEmbedUnimplementedQuarkCMServiceServer() {}

// UnsafeQuarkCMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuarkCMServiceServer will
// result in compilation errors.
type UnsafeQuarkCMServiceServer interface {
	mustEmbedUnimplementedQuarkCMServiceServer()
}

func RegisterQuarkCMServiceServer(s grpc.ServiceRegistrar, srv QuarkCMServiceServer) {
	s.RegisterService(&QuarkCMService_ServiceDesc, srv)
}

func _QuarkCMService_TestPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuarkCMServiceServer).TestPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quarkcmsvc.QuarkCMService/TestPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuarkCMServiceServer).TestPing(ctx, req.(*TestRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuarkCMService_ListNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuarkCMServiceServer).ListNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quarkcmsvc.QuarkCMService/ListNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuarkCMServiceServer).ListNode(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuarkCMService_WatchNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MaxResourceVersionMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuarkCMServiceServer).WatchNode(m, &quarkCMServiceWatchNodeServer{stream})
}

type QuarkCMService_WatchNodeServer interface {
	Send(*NodeMessage) error
	grpc.ServerStream
}

type quarkCMServiceWatchNodeServer struct {
	grpc.ServerStream
}

func (x *quarkCMServiceWatchNodeServer) Send(m *NodeMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _QuarkCMService_ListPod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuarkCMServiceServer).ListPod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quarkcmsvc.QuarkCMService/ListPod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuarkCMServiceServer).ListPod(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuarkCMService_WatchPod_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MaxResourceVersionMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuarkCMServiceServer).WatchPod(m, &quarkCMServiceWatchPodServer{stream})
}

type QuarkCMService_WatchPodServer interface {
	Send(*PodMessage) error
	grpc.ServerStream
}

type quarkCMServiceWatchPodServer struct {
	grpc.ServerStream
}

func (x *quarkCMServiceWatchPodServer) Send(m *PodMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _QuarkCMService_ListService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuarkCMServiceServer).ListService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quarkcmsvc.QuarkCMService/ListService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuarkCMServiceServer).ListService(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuarkCMService_WatchService_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MaxResourceVersionMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuarkCMServiceServer).WatchService(m, &quarkCMServiceWatchServiceServer{stream})
}

type QuarkCMService_WatchServiceServer interface {
	Send(*ServiceMessage) error
	grpc.ServerStream
}

type quarkCMServiceWatchServiceServer struct {
	grpc.ServerStream
}

func (x *quarkCMServiceWatchServiceServer) Send(m *ServiceMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _QuarkCMService_ListEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuarkCMServiceServer).ListEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quarkcmsvc.QuarkCMService/ListEndpoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuarkCMServiceServer).ListEndpoints(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuarkCMService_WatchEndpoints_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MaxResourceVersionMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuarkCMServiceServer).WatchEndpoints(m, &quarkCMServiceWatchEndpointsServer{stream})
}

type QuarkCMService_WatchEndpointsServer interface {
	Send(*EndpointsMessage) error
	grpc.ServerStream
}

type quarkCMServiceWatchEndpointsServer struct {
	grpc.ServerStream
}

func (x *quarkCMServiceWatchEndpointsServer) Send(m *EndpointsMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _QuarkCMService_ListConfigMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuarkCMServiceServer).ListConfigMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quarkcmsvc.QuarkCMService/ListConfigMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuarkCMServiceServer).ListConfigMap(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuarkCMService_WatchConfigMap_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MaxResourceVersionMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuarkCMServiceServer).WatchConfigMap(m, &quarkCMServiceWatchConfigMapServer{stream})
}

type QuarkCMService_WatchConfigMapServer interface {
	Send(*ConfigMapMessage) error
	grpc.ServerStream
}

type quarkCMServiceWatchConfigMapServer struct {
	grpc.ServerStream
}

func (x *quarkCMServiceWatchConfigMapServer) Send(m *ConfigMapMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _QuarkCMService_ListIngress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuarkCMServiceServer).ListIngress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quarkcmsvc.QuarkCMService/ListIngress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuarkCMServiceServer).ListIngress(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuarkCMService_WatchIngress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MaxResourceVersionMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuarkCMServiceServer).WatchIngress(m, &quarkCMServiceWatchIngressServer{stream})
}

type QuarkCMService_WatchIngressServer interface {
	Send(*IngressMessage) error
	grpc.ServerStream
}

type quarkCMServiceWatchIngressServer struct {
	grpc.ServerStream
}

func (x *quarkCMServiceWatchIngressServer) Send(m *IngressMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _QuarkCMService_ListRdmaIngress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuarkCMServiceServer).ListRdmaIngress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quarkcmsvc.QuarkCMService/ListRdmaIngress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuarkCMServiceServer).ListRdmaIngress(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuarkCMService_WatchRdmaIngress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MaxResourceVersionMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuarkCMServiceServer).WatchRdmaIngress(m, &quarkCMServiceWatchRdmaIngressServer{stream})
}

type QuarkCMService_WatchRdmaIngressServer interface {
	Send(*RdmaIngressMessage) error
	grpc.ServerStream
}

type quarkCMServiceWatchRdmaIngressServer struct {
	grpc.ServerStream
}

func (x *quarkCMServiceWatchRdmaIngressServer) Send(m *RdmaIngressMessage) error {
	return x.ServerStream.SendMsg(m)
}

// QuarkCMService_ServiceDesc is the grpc.ServiceDesc for QuarkCMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuarkCMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quarkcmsvc.QuarkCMService",
	HandlerType: (*QuarkCMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestPing",
			Handler:    _QuarkCMService_TestPing_Handler,
		},
		{
			MethodName: "ListNode",
			Handler:    _QuarkCMService_ListNode_Handler,
		},
		{
			MethodName: "ListPod",
			Handler:    _QuarkCMService_ListPod_Handler,
		},
		{
			MethodName: "ListService",
			Handler:    _QuarkCMService_ListService_Handler,
		},
		{
			MethodName: "ListEndpoints",
			Handler:    _QuarkCMService_ListEndpoints_Handler,
		},
		{
			MethodName: "ListConfigMap",
			Handler:    _QuarkCMService_ListConfigMap_Handler,
		},
		{
			MethodName: "ListIngress",
			Handler:    _QuarkCMService_ListIngress_Handler,
		},
		{
			MethodName: "ListRdmaIngress",
			Handler:    _QuarkCMService_ListRdmaIngress_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchNode",
			Handler:       _QuarkCMService_WatchNode_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchPod",
			Handler:       _QuarkCMService_WatchPod_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchService",
			Handler:       _QuarkCMService_WatchService_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchEndpoints",
			Handler:       _QuarkCMService_WatchEndpoints_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchConfigMap",
			Handler:       _QuarkCMService_WatchConfigMap_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchIngress",
			Handler:       _QuarkCMService_WatchIngress_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchRdmaIngress",
			Handler:       _QuarkCMService_WatchRdmaIngress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/connectionmanager/grpc/quarkcmsvc.proto",
}
