apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rdmaingresses.quarksoft.io
spec:
  scope: Cluster
  group: quarksoft.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      port:
                        type: integer
                      service:
                        type: string
                      targetport:
                        type: integer
  names:
    kind: RdmaIngress
    plural: rdmaingresses
    singular: rdmaingress
    shortNames:
      - rin
      - rins
