---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quarkcm-operator
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "endpoints", "configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["quarksoft.io"]
  resources: ["rdmaingresses"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quarkcm-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quarkcm-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quarkcm-operator
subjects:
  - kind: ServiceAccount
    name: quarkcm-operator
    namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: quarkcm-daemon
  namespace: default
spec:
  selector:
    matchLabels:
      job: quarkcm-daemon
  template:
    metadata:
      labels:
        job: quarkcm-daemon
    spec:
      tolerations:
        # The daemon shall run on the master node
        - effect: NoSchedule
          operator: Exists
      serviceAccountName: quarkcm-operator
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      hostPID: true
      volumes:
        - name: quarkcni
          hostPath:
            path: /var
            type: Directory
        - name: quarkcm
          hostPath:
            path: /var/quarkcm
            type: DirectoryOrCreate
      initContainers:
        - image: quarkcm/quarkcni:v0.2.0
          name: node-init
          command: [./node-init.sh]
          securityContext:
            privileged: true
          volumeMounts:
            - name: quarkcni
              mountPath: /home
      containers:
        - name: quarkcm-daemon
          image: quarkcm/quarkcm:v0.2.0
          securityContext:
            privileged: true
          volumeMounts:
            - name: quarkcm
              mountPath: /home
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: quarkrdma-daemon
  namespace: default
spec:
  selector:
    matchLabels:
      job: quarkrdma-daemon
  template:
    metadata:
      labels:
        job: quarkrdma-daemon
    spec:
      tolerations:
        # The daemon shall run on the master node
        - effect: NoSchedule
          operator: Exists
      serviceAccountName: quarkcm-operator
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      hostPID: true
      volumes:
        - name: quarkrdma
          hostPath:
            path: /var/quarkrdma
            type: DirectoryOrCreate
      containers:
        - name: quarkrdma-daemon
          image: quarkcm/rdma_srv:v0.2.0
          securityContext:
            privileged: true
          volumeMounts:
            - name: quarkrdma
              mountPath: /var/quarkrdma
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: quarkegress-daemon
  namespace: default
spec:
  selector:
    matchLabels:
      job: quarkegress-daemon
  template:
    metadata:
      labels:
        job: quarkegress-daemon
    spec:
      tolerations:
        # The daemon shall run on the master node
        - effect: NoSchedule
          operator: Exists
      serviceAccountName: quarkcm-operator
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      hostPID: true
      volumes:
        - name: quarkegress
          hostPath:
            path: /var/quarkrdma
            type: DirectoryOrCreate
      containers:
        - name: quarkegress-daemon
          image: quarkcm/rdma_egress:v0.2.0
          securityContext:
            privileged: true
          volumeMounts:
            - name: quarkegress
              mountPath: /var/quarkrdma
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: quarkingress-daemon
  namespace: default
spec:
  selector:
    matchLabels:
      job: quarkingress-daemon
  template:
    metadata:
      labels:
        job: quarkingress-daemon
    spec:
      tolerations:
        # The daemon shall run on the master node
        - effect: NoSchedule
          operator: Exists
      serviceAccountName: quarkcm-operator
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      hostPID: true
      volumes:
        - name: quarkingress
          hostPath:
            path: /var/quarkrdma
            type: DirectoryOrCreate
      containers:
        - name: quarkingress-daemon
          image: quarkcm/rdma_ingress:v0.2.0
          securityContext:
            privileged: true
          volumeMounts:
            - name: quarkingress
              mountPath: /var/quarkrdma
