apiVersion: quarksoft.io/v1alpha1
kind: RdmaIngress
metadata:
  name: testingress
spec:
  rules:
  - port: 8080
    service: default/test
    targetport: 9000
  - port: 8000
    service: default/test1
    targetport: 9001
